language: java
  
sudo: required

services:
  - docker

install:
  - docker pull mongo

addons:
  sonarcloud:
    organization: "alexfoglia1-github"
    token:
      secure: "ELjNsQjx9JgphDkd+ZYfgw/KcId+LcNjlE5x5YWel6vwDromQuyV9PFhbE8KpC8AkaKWWb9yJyNff4tdoqmS/KqTu4fMAW4PmLTRAs2XM4TS1qgCWMgqUOhoNCTUQ8CAJ5aMmdpyWf6WnqdeZMRvJqbEKNa+YOOfj0GOfb7VuDAcnH3qZFD48kkGPiAtdgpo5arMaGXJoESe7NIhXSOHDrDtdORgnUnF92zMRswDfp3cNPSroEZVEriHKQydSDhsHAbAwFTmdkCBVErFw5yN8nMzIZJsQY8aZiOZsa47Sg1KKT55l3wHMXTBnH1BW6GhxblAYgo/sdm9IwT4q3mIR8IA+2HhpndT3kVM/QF8qBXB4C4AGVqKnjGmmlTyF/TJR+mqb6JcwODDc0Bsrzfuxo/oXN3kXNTA4Ejt4NJsEHxauRAvWacO/hjrjFuwlydBEm9mszE6XeHFZ/5chSXr4DB9CQZjL1nwCH5N7AkNhhSIr36Kvgg3NfPM5l9ksyC2PzqpIEWEal2LpO93Q/xpf1xiMitFJ5wIdR19OsCu+o4BZsJdWeW6EqHyanzvh8TUP8bdjbLZPwAM1LR+ueresAHwJSma5rcKzsuhOqvV2pcGbmm6cLu7gtdmr0NAjpzJs+LusycrEFUNosAVXrAk9SYeppxrP8TFfveCIYTVskY="

script:
  - mvn clean verify -Pjacoco coveralls:report
  - mvn clean verify -Pjacoco sonar:sonar
  - mvn clean verify -Pfailsafe
 
after_failure:
  - cat /home/travis/build/alexfoglia1/attsw-exam/target/surefire-reports/*.txt 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
