language: java
  
sudo: required

services:
  - docker

install:
  - docker pull mongo

addons:
  sonarcloud:
    organization: "alexfoglia1git"
    token:
      secure: "mm8V5rnCcgzqklrQWNaG/f44WTG4SdUJsG4xtzhTVD36d9+IV5qFH2SCg7i+hZEMKTVyX12iYUlR4peAVqbra42SYr+M8otT49lGWLafpDdNKNdhMBasQbOGQ2KEEfW+nYWl+iVg1zx5UpLPRBK2rMHfTiokEXsYhVHPozW+25yQoolOMEm1XS2JIof0PxngyJlFsM7qy8JYCVE3BrV3s5WODQaOpvxPb6vJ3eG62PAQ3rrdxFEGtMPk9dprLqw5rqslrExqC/7GM2awFTGVMR39jVJZ17nBw6/Vz8rEmVcoqffqMJ0DmhQ9AFCGTvrZk4i8sIIY4i73BSAXqJJyf1ITMhpeEat+lZZaIjouH8HDHIxGb0qxcGFWBzS7aKpjrJMabX8516rV6gPSK2lpxHzBCCZeZxO0KpCdAkWvg/J2ELcdQy8IZdz20ZPbj4PYO+swl63gZKwoNRHHaS5DKDJje1nuIAtWmWrs5jreup+X5SD2EFzm2sUi8FsdXpQiTHNyApDlsuDJjqlFE2PfiVhp18EumBO3ah0M6DP/PcETRgXt7AoPyg5pmTInYwTI5eE0B39YgE5qdYrXoDPCdNPnRgpJrz6s+UqsngguCMLdmIQVgC5mb41B7P5QNSA/bqlqVHswd4i0R8O5UP73kMMi7QqevqvKUQdL2mF7OE0="
env:
  - DISPLAY=:99.0

before_install:
      sh -e /etc/init.d/xvfb start;
    
script:
  - mvn clean verify -Pjacoco coveralls:report
  - mvn clean verify -Pjacoco sonar:sonar
  - mvn clean verify -Pfailsafe
 
after_failure:
  - cat /home/travis/build/alexfoglia1/attsw-exam/target/surefire-reports/*.txt 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

